// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin/v1/handshake.proto

// Kind-agnostic handshake. Every Acciew plugin binary, whatever it does,
// serves this service. The host calls Hello before it knows what the plugin
// is, then dials the kind-specific service the plugin offered.
//
// Versions independently of every kind. Adding a kind is a new package under
// api/<kind>/v1 plus a new string in Offering.kind; never a change here.
//
// Lint: buf STANDARD. PACKAGE_DIRECTORY_MATCH is excepted for this file
// (package acciew.plugin.v1 lives under api/plugin/v1).

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandshakeService_Hello_FullMethodName = "/acciew.plugin.v1.HandshakeService/Hello"
)

// HandshakeServiceClient is the client API for HandshakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HandshakeService is the one service every plugin binary must expose.
type HandshakeServiceClient interface {
	// Hello exchanges what each side can speak. Called once per plugin launch.
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type handshakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandshakeServiceClient(cc grpc.ClientConnInterface) HandshakeServiceClient {
	return &handshakeServiceClient{cc}
}

func (c *handshakeServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandshakeServiceServer is the server API for HandshakeService service.
// All implementations must embed UnimplementedHandshakeServiceServer
// for forward compatibility.
//
// HandshakeService is the one service every plugin binary must expose.
type HandshakeServiceServer interface {
	// Hello exchanges what each side can speak. Called once per plugin launch.
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHandshakeServiceServer()
}

// UnimplementedHandshakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandshakeServiceServer struct{}

func (UnimplementedHandshakeServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHandshakeServiceServer) mustEmbedUnimplementedHandshakeServiceServer() {}
func (UnimplementedHandshakeServiceServer) testEmbeddedByValue()                          {}

// UnsafeHandshakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandshakeServiceServer will
// result in compilation errors.
type UnsafeHandshakeServiceServer interface {
	mustEmbedUnimplementedHandshakeServiceServer()
}

func RegisterHandshakeServiceServer(s grpc.ServiceRegistrar, srv HandshakeServiceServer) {
	// If the following call panics, it indicates UnimplementedHandshakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandshakeService_ServiceDesc, srv)
}

func _HandshakeService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandshakeService_ServiceDesc is the grpc.ServiceDesc for HandshakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandshakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acciew.plugin.v1.HandshakeService",
	HandlerType: (*HandshakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HandshakeService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/handshake.proto",
}
