// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin/v1/handshake.proto

// Kind-agnostic handshake. Every Acciew plugin binary, whatever it does,
// serves this service. The host calls Hello before it knows what the plugin
// is, then dials the kind-specific service the plugin offered.
//
// Versions independently of every kind. Adding a kind is a new package under
// api/<kind>/v1 plus a new string in Offering.kind; never a change here.
//
// Lint: buf STANDARD. PACKAGE_DIRECTORY_MATCH is excepted for this file
// (package acciew.plugin.v1 lives under api/plugin/v1).

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloRequest tells the plugin what the host can speak.
type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every (kind, version) the host can speak, so a plugin that cannot agree
	// can log a message naming both sides' ranges.
	HostSupports []*Offering `protobuf:"bytes,1,rep,name=host_supports,json=hostSupports,proto3" json:"host_supports,omitempty"`
	// Host build version, for the plugin's logs.
	HostVersion   string `protobuf:"bytes,2,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_plugin_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetHostSupports() []*Offering {
	if x != nil {
		return x.HostSupports
	}
	return nil
}

func (x *HelloRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

// HelloResponse tells the host what the plugin is and what it can speak.
type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable plugin identifier, e.g. "keycloak". Not the configured instance.
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// Plugin build version, semver.
	PluginVersion string `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// Every (kind, version) this binary implements. A binary may offer several
	// kinds and several versions of one kind.
	Offerings     []*Offering `protobuf:"bytes,3,rep,name=offerings,proto3" json:"offerings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_plugin_v1_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *HelloResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *HelloResponse) GetOfferings() []*Offering {
	if x != nil {
		return x.Offerings
	}
	return nil
}

// Offering is one kind at one contract major version.
type Offering struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registered kind name. Defined now: "collector". Reserved for later
	// contracts and never to be reused for anything else: "notifier",
	// "exporter", "enricher", "revoker".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Major version of that kind's contract: 1 for acciew.collector.v1.
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Offering) Reset() {
	*x = Offering{}
	mi := &file_plugin_v1_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offering) ProtoMessage() {}

func (x *Offering) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offering.ProtoReflect.Descriptor instead.
func (*Offering) Descriptor() ([]byte, []int) {
	return file_plugin_v1_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *Offering) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Offering) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

var File_plugin_v1_handshake_proto protoreflect.FileDescriptor

const file_plugin_v1_handshake_proto_rawDesc = "" +
	"\n" +
	"\x19plugin/v1/handshake.proto\x12\x10acciew.plugin.v1\"r\n" +
	"\fHelloRequest\x12?\n" +
	"\rhost_supports\x18\x01 \x03(\v2\x1a.acciew.plugin.v1.OfferingR\fhostSupports\x12!\n" +
	"\fhost_version\x18\x02 \x01(\tR\vhostVersion\"\x91\x01\n" +
	"\rHelloResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x128\n" +
	"\tofferings\x18\x03 \x03(\v2\x1a.acciew.plugin.v1.OfferingR\tofferings\"I\n" +
	"\bOffering\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion2\\\n" +
	"\x10HandshakeService\x12H\n" +
	"\x05Hello\x12\x1e.acciew.plugin.v1.HelloRequest\x1a\x1f.acciew.plugin.v1.HelloResponseB/Z-go.acciew.io/collector/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_handshake_proto_rawDescOnce sync.Once
	file_plugin_v1_handshake_proto_rawDescData []byte
)

func file_plugin_v1_handshake_proto_rawDescGZIP() []byte {
	file_plugin_v1_handshake_proto_rawDescOnce.Do(func() {
		file_plugin_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_handshake_proto_rawDesc), len(file_plugin_v1_handshake_proto_rawDesc)))
	})
	return file_plugin_v1_handshake_proto_rawDescData
}

var file_plugin_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_v1_handshake_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: acciew.plugin.v1.HelloRequest
	(*HelloResponse)(nil), // 1: acciew.plugin.v1.HelloResponse
	(*Offering)(nil),      // 2: acciew.plugin.v1.Offering
}
var file_plugin_v1_handshake_proto_depIdxs = []int32{
	2, // 0: acciew.plugin.v1.HelloRequest.host_supports:type_name -> acciew.plugin.v1.Offering
	2, // 1: acciew.plugin.v1.HelloResponse.offerings:type_name -> acciew.plugin.v1.Offering
	0, // 2: acciew.plugin.v1.HandshakeService.Hello:input_type -> acciew.plugin.v1.HelloRequest
	1, // 3: acciew.plugin.v1.HandshakeService.Hello:output_type -> acciew.plugin.v1.HelloResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_v1_handshake_proto_init() }
func file_plugin_v1_handshake_proto_init() {
	if File_plugin_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_handshake_proto_rawDesc), len(file_plugin_v1_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_handshake_proto_goTypes,
		DependencyIndexes: file_plugin_v1_handshake_proto_depIdxs,
		MessageInfos:      file_plugin_v1_handshake_proto_msgTypes,
	}.Build()
	File_plugin_v1_handshake_proto = out.File
	file_plugin_v1_handshake_proto_goTypes = nil
	file_plugin_v1_handshake_proto_depIdxs = nil
}
