// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: collector/v1/collector.proto

// Acciew collector contract, version 1.
//
// Design review: docs/design/three-source-mapping.md (requirements R1-R15).
// Shape decisions: docs/adr/0006-collector-contract-shape.md.
// Coarse AWS entitlements: docs/adr/0003-coarse-entitlements-for-aws-iam.md.
//
// Transport-neutral. This file is a schema; nothing in it assumes gRPC.
//
// Compatibility (sdk/go/README.md): field numbers are never reused; a removed
// field's number goes to `reserved` in the same commit; unknown fields and
// unknown non-zero enum values are preserved and tolerated, never rejected.
// `reserved` statements record fields considered and rejected; they are
// permanent under buf's FILE breaking category, and future fields take new
// numbers rather than claiming a reserved one.
//
// Zero-valued enums. Every enum has <NAME>_UNSPECIFIED = 0 because proto3 and
// buf require it. On the wire it is INVALID everywhere, with one stated
// exception: ScopeProbe.activity and ScopeOutcome.activity are meaningful only
// when Capabilities.activity is true, so a plugin that produces no activity
// data leaves them unset. Nothing else in this file may be zero.
//
// Where "we do not know" is an honest answer, an explicit _UNKNOWN value
// exists and is never the zero value.
//
// validate.go in this package is the single implementation of that rule and of
// every other rule protobuf cannot express. It is called by the SDK before an
// emit, by the host on receipt -- which is the load-bearing one, since a
// plugin written against another transport in another language never touches
// our SDK -- and by the conformance suite. The SDK, host and suite are being
// built; until each lands, its call site is intent rather than fact.
//
// Lint: buf STANDARD. PACKAGE_DIRECTORY_MATCH is excepted for this file.

package collectorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_Describe_FullMethodName       = "/acciew.collector.v1.CollectorService/Describe"
	CollectorService_ValidateConfig_FullMethodName = "/acciew.collector.v1.CollectorService/ValidateConfig"
	CollectorService_TestConnection_FullMethodName = "/acciew.collector.v1.CollectorService/TestConnection"
	CollectorService_Collect_FullMethodName        = "/acciew.collector.v1.CollectorService/Collect"
	CollectorService_Revoke_FullMethodName         = "/acciew.collector.v1.CollectorService/Revoke"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CollectorService is the "collector" kind at protocol version 1.
type CollectorServiceClient interface {
	// Describe returns static self-description: capabilities, declared
	// limitations, activity signals. Takes no config; anything
	// config-dependent belongs in TestConnection.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// ValidateConfig checks the opaque config document plugin-side. It never
	// contacts the source. R6.
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	// TestConnection contacts the source, enumerates the scopes the
	// credentials reach, and reports reachability and per-scope activity
	// availability. R7.
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	// Collect streams the inventory. Resumable by cursor. A stream is
	// successful only if its last event is a Completion with VERDICT_COMPLETE;
	// the host treats every other ending as an error. R5.
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CollectResponse], error)
	// Revoke is DECLARED, NOT IMPLEMENTED in this release. Every collector
	// answers REVOKE_OUTCOME_NOT_SUPPORTED and declares capabilities.revoke =
	// false; the conformance suite fails a plugin that does otherwise. The
	// shape is fixed now so a later implementation is not a contract change.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, CollectorService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, CollectorService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, CollectorService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CollectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], CollectorService_Collect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectRequest, CollectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_CollectClient = grpc.ServerStreamingClient[CollectResponse]

func (c *collectorServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, CollectorService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
//
// CollectorService is the "collector" kind at protocol version 1.
type CollectorServiceServer interface {
	// Describe returns static self-description: capabilities, declared
	// limitations, activity signals. Takes no config; anything
	// config-dependent belongs in TestConnection.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// ValidateConfig checks the opaque config document plugin-side. It never
	// contacts the source. R6.
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	// TestConnection contacts the source, enumerates the scopes the
	// credentials reach, and reports reachability and per-scope activity
	// availability. R7.
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	// Collect streams the inventory. Resumable by cursor. A stream is
	// successful only if its last event is a Completion with VERDICT_COMPLETE;
	// the host treats every other ending as an error. R5.
	Collect(*CollectRequest, grpc.ServerStreamingServer[CollectResponse]) error
	// Revoke is DECLARED, NOT IMPLEMENTED in this release. Every collector
	// answers REVOKE_OUTCOME_NOT_SUPPORTED and declares capabilities.revoke =
	// false; the conformance suite fails a plugin that does otherwise. The
	// shape is fixed now so a later implementation is not a contract change.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedCollectorServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedCollectorServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedCollectorServiceServer) Collect(*CollectRequest, grpc.ServerStreamingServer[CollectResponse]) error {
	return status.Error(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedCollectorServiceServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServiceServer).Collect(m, &grpc.GenericServerStream[CollectRequest, CollectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_CollectServer = grpc.ServerStreamingServer[CollectResponse]

func _CollectorService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acciew.collector.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _CollectorService_Describe_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _CollectorService_ValidateConfig_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _CollectorService_TestConnection_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _CollectorService_Revoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _CollectorService_Collect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collector/v1/collector.proto",
}
